name: Node.js Test

on:
  push:
    branches: ['develop', 'master']
  pull_request:
    branches: ['develop', 'master']

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: ThisIsAStrongP@assword!SortOf
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
        options: --name=mssql --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'ThisIsAStrongP@assword!SortOf' -Q 'SELECT 1'" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Create MS SQL Database and run test
        run: |
          sudo apt-get update && sudo apt-get install -y mssql-tools
          /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'ThisIsAStrongP@assword!SortOf' -Q 'CREATE DATABASE nightwatchDb'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install chromedriver@108
      - run: npm install
      - run: npm test
