name: Setup DB and Test

on:
  push:
    branches: ['develop', 'master']
  pull_request:
    branches: ['develop', 'master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker image build --file ./test/Dockerfile --tag nightwatchsqldb:1 .
  test:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: nightwatchsqldb:1
        env:
          SA_PASSWORD: ThisIsAStrongP@assword!SortOf
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/setup-node@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install chromedriver@latest
      - run: npm install
      - run: npm run lint
      - run: npm test
