name: Setup DB and Test

on:
  push:
    branches: ['develop', 'master']
  pull_request:
    branches: ['develop', 'master']

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: MyTestPassword
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/setup-node@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install chromedriver@latest
      - run: npm install
      - run: npm run lint
      - run: npm test
