name: Node.js Test

on:
  push:
    branches: ['develop', 'master']
  pull_request:
    branches: ['develop', 'master']

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: ThisIsAStrongP@assword!SortOf
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install chromedriver@108
      - run: npm install
      - run: npm test
